### ISSUE TITLE
Implement Iterator trait instead of PointIterator::next() 

### ISSUE THREAD

**Issue by dunnock** [invis87/drawing_robot#1]
This will allow to use startdard language facilities to iterate:

https://github.com/invis87/drawing_robot/blob/7beebe360b332ad70e8b8239e6297efd0914d2ef/rust/src/svg_curve.rs#L55

**Comment by pronvis** [comment]
Maybe I don't get your point, but I already implement it:https://github.com/invis87/drawing_robot/blob/e30e7b0f9eb13b490adb1c321bd5b70752b1df0b/rust/src/svg/svg_curve.rs#L174
Did you mean that or something else?

**Comment by dunnock** [comment]
That's and extra call in call stack also not obvious. If you want to show that PointIterator extends Iterator you may define it as supertrait:
```
trait PointIterator: Iterator {
   ....
}
```
That's more ideomatic way
read more https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#using-supertraits-to-require-one-traits-functionality-within-another-trait

**Comment by pronvis** [comment]
Hmmm, thanks!
Like this: https://github.com/invis87/drawing_robot/pull/2 ?
